### ISSUE TITLE
Error Message when creating a new account

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#156]
Title: 
`frappe.core.doctype.user.user.create_contact`

`Traceback (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 117, in execute_job
    method(**kwargs)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 1002, in create_contact
    contact.insert(ignore_permissions=True, ignore_links=ignore_links, ignore_mandatory=ignore_mandatory)
  File "apps/frappe/frappe/model/document.py", line 233, in insert
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 841, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg),
  File "apps/frappe/frappe/__init__.py", line 447, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 426, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 381, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: itsharshie@gmail.com`

**Comment by ksandeep911** [comment]
Why does this error show up on my Error Log?
