### ISSUE TITLE
First Error

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#168]
Getting this error while logging in: 

### App Versions
```
{
	"frappe": "14.0.0-dev",
	"helpdesk": "0.0.1"
}
```
### Route
```
Workspaces/HelpDesk
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1233, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 717, in get_email_awaiting
    frappe.qb.update(user_email_table).set(user_email_table.user_email_table, 0).where(user_email_table.parent == user).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 59, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs) # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 152, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'user_email_table' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"user": "itsharshie@gmail.com"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.core.doctype.user.user.get_email_awaiting"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'user_email_table' in 'field list'\")"
}
```

**Comment by kamaljohnson** [comment]
This seems like a framework issue, which is fixed now I guess since no such problem has been noted after this
