### ISSUE TITLE
Agent Group Permission Error

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#271]
No tickets are fetched and getting this error: 

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1259, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 47, in get_list
    return frappe.get_list(**args)
  File "apps/frappe/frappe/__init__.py", line 1494, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 46, in execute
    raise frappe.PermissionError(self.doctype)
frappe.exceptions.PermissionError: Agent Group`

**Comment by kamaljohnson** [comment]
Resolved in #714
