### ISSUE TITLE
Signup on frappedesk.com is not working

### ISSUE THREAD

**Issue by michalls01** [frappe/desk#603]
The signup form is not working, showing spinning wheel and the label on the signup button "signing up". Below is a console log.

Failed to load resource: the server responded with a status of 500 ()
frappe-web.bundle.E3ESOUMB.js:1709 
        
       Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 69, in execute_cmd
    return run_server_script(server_script)
  File "apps/frappe/frappe/handler.py", line 87, in run_server_script
    response = frappe.get_doc("Server Script", server_script).execute_method()
  File "apps/frappe/frappe/core/doctype/server_script/server_script.py", line 89, in execute_method
    _globals, _locals = safe_exec(self.script)
  File "apps/frappe/frappe/utils/safe_exec.py", line 69, in safe_exec
    exec(compile_restricted(script), exec_globals, _locals)  # pylint: disable=exec-used
  File "<unknown>", line 50, in <module>
  File "apps/frappe/frappe/integrations/utils.py", line 37, in make_post_request
    return make_request("POST", url, **kwargs)
  File "apps/frappe/frappe/integrations/utils.py", line 29, in make_request
    raise exc
  File "apps/frappe/frappe/integrations/utils.py", line 21, in make_request
    frappe.flags.integration_request.raise_for_status()
  File "env/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 417 Client Error: EXPECTATION FAILED for url: https://frappecloud.com/api/method/press.api.saas.account_request

process_response @ frappe-web.bundle.E3ESOUMB.js:1709
signup:1 
        
       The resource https://frappedesk.com/website_script.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
signup:1 
        
       The resource https://frappedesk.com/website_script.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
signup:1 
        
       The resource https://frappedesk.com/website_script.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by kamaljohnson** [comment]
@michalls01, since the country field in the singup flow is a plain text field and the validation is being done at the backend (FC) there where validation issues because people don't properly input there country name

I have added a country select dropdown in the signup page, this will fix this issue
