### ISSUE TITLE
System manger permission error

### ISSUE THREAD

**Issue by harshit-30** [frappe/desk#696]
Scenario: Added a new agent with all the framework permissions except `System Manager` and going to /frappedesk/tickets gives the following error: 

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1503, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 84, in get
    raise frappe.PermissionError
frappe.exceptions.PermissionError`

**Comment by kamaljohnson** [comment]
Fixed in #714
